title: "Duckkyun Blog"
description: "GitHub Pages + Jekyll + Minimal Mistakes"
url: "https://duckkyun.github.io"
baseurl: ""
locale: "ko-KR"
timezone: "Asia/Seoul"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"
search: true

author:
  name: "duckkyun"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: ""
    values:
      author_profile: false

permalink: /:categories/:title/

collections:
  posts:
    output: true

include:
  - _pages

atom_feed:
  hide: true
